[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@1.22.22 --activate",
  "yarn install --frozen-lockfile --legacy-peer-deps"
]

[phases.build]
cmds = ["DISABLE_ESLINT_PLUGIN=true GENERATE_SOURCEMAP=false yarn build"]

[start]
cmd = "npx serve -s build -l $PORT"
